// TM Forum SID R22 Data Models — shared entity library + per-product declarations
const TMFDataModels = (() => {

  // ── Core SID entity schemas ──────────────────────────────────────────────────
  // Each attribute: { name, type, mult, req, sidRef, description }
  const SID_ENTITIES = {

    CustomerAccount: {
      module: 'Customer Domain',
      specRef: 'GB922 §6',
      attributes: [
        { name: 'id',                       type: 'String',                    mult: '1',    req: true,  sidRef: 'RootEntity.id',                      description: 'Unique identifier' },
        { name: 'href',                     type: 'String',                    mult: '0..1', req: false, sidRef: 'RootEntity.href',                    description: 'Canonical hypertext reference' },
        { name: 'name',                     type: 'String',                    mult: '0..1', req: false, sidRef: 'CustomerAccount.name',               description: 'Account display name' },
        { name: 'accountType',              type: 'String',                    mult: '0..1', req: false, sidRef: 'CustomerAccount.accountType',        description: 'prepaid | postpaid | hybrid | enterprise' },
        { name: 'status',                   type: 'AccountStateType',          mult: '1',    req: true,  sidRef: 'CustomerAccount.status',             description: 'Lifecycle state: created | active | closed | suspended' },
        { name: 'creditLimit',              type: 'Money',                     mult: '0..1', req: false, sidRef: 'CustomerAccount.creditLimit',        description: 'Maximum credit extended to customer' },
        { name: 'lastModified',             type: 'DateTime',                  mult: '0..1', req: false, sidRef: 'CustomerAccount.lastModified',       description: 'Timestamp of last record change' },
        { name: 'billingCycleSpecification',type: 'BillingCycleSpecificationRef', mult: '0..1', req: false, sidRef: 'CustomerAccount.billingCycleSpec', description: 'Reference to billing cycle definition' },
        { name: 'relatedParty',             type: 'RelatedParty[]',            mult: '1..*', req: true,  sidRef: 'CustomerAccount.relatedParty',       description: 'Individual or Organisation owning this account' },
        { name: 'financialAccount',         type: 'FinancialAccountRef[]',     mult: '0..*', req: false, sidRef: 'CustomerAccount.financialAccount',   description: 'Associated financial accounts' },
      ],
    },

    Individual: {
      module: 'Party Domain',
      specRef: 'GB922 §5',
      attributes: [
        { name: 'id',             type: 'String',          mult: '1',    req: true,  sidRef: 'Individual.id',            description: 'Unique identifier' },
        { name: 'href',           type: 'String',          mult: '0..1', req: false, sidRef: 'Individual.href',          description: 'Canonical hypertext reference' },
        { name: 'givenName',      type: 'String',          mult: '0..1', req: false, sidRef: 'Individual.givenName',     description: 'First / given name' },
        { name: 'familyName',     type: 'String',          mult: '0..1', req: false, sidRef: 'Individual.familyName',    description: 'Family / surname' },
        { name: 'fullName',       type: 'String',          mult: '0..1', req: false, sidRef: 'Individual.fullName',      description: 'Full formatted name' },
        { name: 'gender',         type: 'GenderType',      mult: '0..1', req: false, sidRef: 'Individual.gender',        description: 'Gender enumeration' },
        { name: 'nationality',    type: 'String',          mult: '0..1', req: false, sidRef: 'Individual.nationality',   description: 'ISO 3166-1 alpha-2 country code' },
        { name: 'birthDate',      type: 'Date',            mult: '0..1', req: false, sidRef: 'Individual.birthDate',     description: 'Date of birth' },
        { name: 'status',         type: 'String',          mult: '0..1', req: false, sidRef: 'Individual.status',        description: 'initialized | validated | deceaded' },
        { name: 'contactMedium',  type: 'ContactMedium[]', mult: '0..*', req: false, sidRef: 'Individual.contactMedium', description: 'Email, phone, postal addresses' },
        { name: 'partyCharacteristic', type: 'Characteristic[]', mult: '0..*', req: false, sidRef: 'Individual.partyCharacteristic', description: 'KYC and custom attributes' },
      ],
    },

    ProductOffering: {
      module: 'Product Domain',
      specRef: 'GB922 §8 / TMF620',
      attributes: [
        { name: 'id',                    type: 'String',                     mult: '1',    req: true,  sidRef: 'ProductOffering.id',                   description: 'Unique identifier' },
        { name: 'href',                  type: 'String',                     mult: '0..1', req: false, sidRef: 'ProductOffering.href',                 description: 'Canonical hypertext reference' },
        { name: 'name',                  type: 'String',                     mult: '1',    req: true,  sidRef: 'ProductOffering.name',                 description: 'Commercial name of the offering' },
        { name: 'description',           type: 'String',                     mult: '0..1', req: false, sidRef: 'ProductOffering.description',          description: 'Marketing description' },
        { name: 'isBundle',              type: 'Boolean',                    mult: '1',    req: true,  sidRef: 'ProductOffering.isBundle',             description: 'True if this is a bundle of offerings' },
        { name: 'isSellable',            type: 'Boolean',                    mult: '0..1', req: false, sidRef: 'ProductOffering.isSellable',           description: 'Can be sold standalone' },
        { name: 'lifecycleStatus',       type: 'String',                     mult: '1',    req: true,  sidRef: 'ProductOffering.lifecycleStatus',      description: 'In Study | In Design | Active | Retired | Obsolete' },
        { name: 'validFor',              type: 'TimePeriod',                 mult: '0..1', req: false, sidRef: 'ProductOffering.validFor',             description: 'Effective date range' },
        { name: 'version',               type: 'String',                     mult: '0..1', req: false, sidRef: 'ProductOffering.version',              description: 'Offering version string' },
        { name: 'productSpecification',  type: 'ProductSpecificationRef',    mult: '0..1', req: false, sidRef: 'ProductOffering.productSpecification', description: 'Technical specification backing this offering' },
        { name: 'productOfferingPrice',  type: 'ProductOfferingPriceRef[]',  mult: '0..*', req: false, sidRef: 'ProductOffering.productOfferingPrice', description: 'Associated price definitions' },
        { name: 'channel',               type: 'ChannelRef[]',               mult: '0..*', req: false, sidRef: 'ProductOffering.channel',              description: 'Sales channels where offered' },
      ],
    },

    ProductOrder: {
      module: 'Product Domain',
      specRef: 'GB922 §8 / TMF622',
      attributes: [
        { name: 'id',                      type: 'String',                mult: '1',    req: true,  sidRef: 'ProductOrder.id',                     description: 'Unique identifier' },
        { name: 'href',                    type: 'String',                mult: '0..1', req: false, sidRef: 'ProductOrder.href',                   description: 'Canonical hypertext reference' },
        { name: 'externalId',              type: 'String',                mult: '0..1', req: false, sidRef: 'ProductOrder.externalId',             description: 'External channel reference number' },
        { name: 'priority',                type: 'String',                mult: '0..1', req: false, sidRef: 'ProductOrder.priority',               description: '0 (highest) – 4 (lowest)' },
        { name: 'requestedCompletionDate', type: 'DateTime',              mult: '0..1', req: false, sidRef: 'ProductOrder.requestedCompletionDate', description: 'Customer requested completion date' },
        { name: 'state',                   type: 'ProductOrderStateType', mult: '1',    req: true,  sidRef: 'ProductOrder.state',                  description: 'acknowledged | inProgress | completed | failed | cancelled' },
        { name: 'orderDate',               type: 'DateTime',              mult: '1',    req: true,  sidRef: 'ProductOrder.orderDate',              description: 'Date order was placed' },
        { name: 'channel',                 type: 'ChannelRef',            mult: '0..1', req: false, sidRef: 'ProductOrder.channel',                description: 'Sales channel that originated order' },
        { name: 'billingAccount',          type: 'BillingAccountRef',     mult: '0..1', req: false, sidRef: 'ProductOrder.billingAccount',         description: 'Account that will be billed' },
        { name: 'relatedParty',            type: 'RelatedParty[]',        mult: '1..*', req: true,  sidRef: 'ProductOrder.relatedParty',           description: 'Customer and other involved parties' },
        { name: 'productOrderItem',        type: 'ProductOrderItem[]',    mult: '1..*', req: true,  sidRef: 'ProductOrder.productOrderItem',       description: 'Line items in this order' },
      ],
    },

    Promotion: {
      module: 'Product Domain',
      specRef: 'GB922 §8 / TMF671',
      attributes: [
        { name: 'id',          type: 'String',              mult: '1',    req: true,  sidRef: 'Promotion.id',          description: 'Unique identifier' },
        { name: 'href',        type: 'String',              mult: '0..1', req: false, sidRef: 'Promotion.href',        description: 'Canonical hypertext reference' },
        { name: 'name',        type: 'String',              mult: '1',    req: true,  sidRef: 'Promotion.name',        description: 'Commercial promotion name' },
        { name: 'description', type: 'String',              mult: '0..1', req: false, sidRef: 'Promotion.description', description: 'Marketing description' },
        { name: 'lastUpdate',  type: 'DateTime',            mult: '0..1', req: false, sidRef: 'Promotion.lastUpdate',  description: 'Last modification timestamp' },
        { name: 'status',      type: 'PromotionStatusType', mult: '1',    req: true,  sidRef: 'Promotion.status',      description: 'draft | active | expired | cancelled' },
        { name: 'validFor',    type: 'TimePeriod',          mult: '0..1', req: false, sidRef: 'Promotion.validFor',    description: 'Promotion active date range' },
        { name: 'pattern',     type: 'PromotionPattern[]',  mult: '0..*', req: false, sidRef: 'Promotion.pattern',     description: 'Eligibility and discount rules' },
      ],
    },

    Service: {
      module: 'Service Domain',
      specRef: 'GB922 §9',
      attributes: [
        { name: 'id',                   type: 'String',             mult: '1',    req: true,  sidRef: 'Service.id',                  description: 'Unique service instance identifier' },
        { name: 'href',                 type: 'String',             mult: '0..1', req: false, sidRef: 'Service.href',                description: 'Canonical hypertext reference' },
        { name: 'name',                 type: 'String',             mult: '0..1', req: false, sidRef: 'Service.name',                description: 'Human-readable service name' },
        { name: 'category',             type: 'String',             mult: '0..1', req: false, sidRef: 'Service.category',            description: 'Service domain classification' },
        { name: 'serviceType',          type: 'String',             mult: '0..1', req: false, sidRef: 'Service.serviceType',         description: 'Type e.g. VoLTE, broadband, IoT' },
        { name: 'state',                type: 'ServiceStateType',   mult: '1',    req: true,  sidRef: 'Service.state',               description: 'feasibility | designed | reserved | active | terminated' },
        { name: 'isBundle',             type: 'Boolean',            mult: '1',    req: true,  sidRef: 'Service.isBundle',            description: 'True if composed from component services' },
        { name: 'startDate',            type: 'DateTime',           mult: '0..1', req: false, sidRef: 'Service.startDate',           description: 'Service activation timestamp' },
        { name: 'endDate',              type: 'DateTime',           mult: '0..1', req: false, sidRef: 'Service.endDate',             description: 'Service termination timestamp' },
        { name: 'serviceCharacteristic',type: 'Characteristic[]',   mult: '0..*', req: false, sidRef: 'Service.serviceCharacteristic', description: 'Configuration parameters (MSISDN, APN, QoS tier…)' },
        { name: 'supportingResource',   type: 'ResourceRef[]',      mult: '0..*', req: false, sidRef: 'Service.supportingResource',  description: 'Network resources realising this service' },
        { name: 'relatedParty',         type: 'RelatedParty[]',     mult: '0..*', req: false, sidRef: 'Service.relatedParty',        description: 'Customer and operation centre parties' },
      ],
    },

    ServiceLevelAgreement: {
      module: 'Service Domain',
      specRef: 'GB922 §9 / TMF623',
      attributes: [
        { name: 'id',             type: 'String',            mult: '1',    req: true,  sidRef: 'ServiceLevelAgreement.id',             description: 'Unique identifier' },
        { name: 'href',           type: 'String',            mult: '0..1', req: false, sidRef: 'ServiceLevelAgreement.href',           description: 'Canonical hypertext reference' },
        { name: 'name',           type: 'String',            mult: '1',    req: true,  sidRef: 'ServiceLevelAgreement.name',           description: 'SLA name' },
        { name: 'description',    type: 'String',            mult: '0..1', req: false, sidRef: 'ServiceLevelAgreement.description',    description: 'SLA description and scope' },
        { name: 'version',        type: 'String',            mult: '0..1', req: false, sidRef: 'ServiceLevelAgreement.version',        description: 'Version string' },
        { name: 'validFor',       type: 'TimePeriod',        mult: '0..1', req: false, sidRef: 'ServiceLevelAgreement.validFor',       description: 'Effective date range' },
        { name: 'state',          type: 'String',            mult: '0..1', req: false, sidRef: 'ServiceLevelAgreement.state',          description: 'initialized | active | terminated' },
        { name: 'approved',       type: 'Boolean',           mult: '0..1', req: false, sidRef: 'ServiceLevelAgreement.approved',       description: 'Whether SLA has been formally approved' },
        { name: 'relatedParty',   type: 'RelatedParty[]',   mult: '1..*', req: true,  sidRef: 'ServiceLevelAgreement.relatedParty',   description: 'Provider and customer parties' },
        { name: 'rule',           type: 'SLARule[]',         mult: '0..*', req: false, sidRef: 'ServiceLevelAgreement.rule',           description: 'Objective thresholds and measurement rules' },
      ],
    },

    ServiceProblem: {
      module: 'Service Domain',
      specRef: 'GB922 §9 / TMF656',
      attributes: [
        { name: 'id',                    type: 'String',              mult: '1',    req: true,  sidRef: 'ServiceProblem.id',                    description: 'Unique identifier' },
        { name: 'href',                  type: 'String',              mult: '0..1', req: false, sidRef: 'ServiceProblem.href',                  description: 'Canonical hypertext reference' },
        { name: 'priority',              type: 'String',              mult: '1',    req: true,  sidRef: 'ServiceProblem.priority',              description: '1 (Critical) – 4 (Low)' },
        { name: 'severity',              type: 'String',              mult: '1',    req: true,  sidRef: 'ServiceProblem.severity',              description: 'critical | major | minor | warning' },
        { name: 'status',                type: 'ServiceProblemStateType', mult: '1', req: true, sidRef: 'ServiceProblem.status',               description: 'submitted | inProgress | resolved | closed' },
        { name: 'description',           type: 'String',              mult: '0..1', req: false, sidRef: 'ServiceProblem.description',           description: 'Problem description' },
        { name: 'category',              type: 'String',              mult: '0..1', req: false, sidRef: 'ServiceProblem.category',              description: 'Problem category (network, service, customer)' },
        { name: 'problemOccurrenceDate', type: 'DateTime',            mult: '1',    req: true,  sidRef: 'ServiceProblem.problemOccurrenceDate', description: 'When problem was first detected' },
        { name: 'resolutionDate',        type: 'DateTime',            mult: '0..1', req: false, sidRef: 'ServiceProblem.resolutionDate',        description: 'Timestamp of resolution' },
        { name: 'affectedService',       type: 'ServiceRef[]',        mult: '1..*', req: true,  sidRef: 'ServiceProblem.affectedService',       description: 'Services impacted by this problem' },
        { name: 'associatedSLA',         type: 'SLARef[]',            mult: '0..*', req: false, sidRef: 'ServiceProblem.associatedSLA',         description: 'SLAs that may be breached' },
        { name: 'note',                  type: 'Note[]',              mult: '0..*', req: false, sidRef: 'ServiceProblem.note',                  description: 'Chronological work log entries' },
      ],
    },

    Resource: {
      module: 'Resource Domain',
      specRef: 'GB922 §10 / TMF639',
      attributes: [
        { name: 'id',                   type: 'String',                         mult: '1',    req: true,  sidRef: 'Resource.id',                    description: 'Unique identifier' },
        { name: 'href',                 type: 'String',                         mult: '0..1', req: false, sidRef: 'Resource.href',                  description: 'Canonical hypertext reference' },
        { name: 'name',                 type: 'String',                         mult: '0..1', req: false, sidRef: 'Resource.name',                  description: 'Resource name' },
        { name: 'category',             type: 'String',                         mult: '0..1', req: false, sidRef: 'Resource.category',              description: 'Resource category / type class' },
        { name: 'resourceType',         type: 'String',                         mult: '0..1', req: false, sidRef: 'Resource.resourceType',          description: 'physical | logical | compound' },
        { name: 'resourceVersion',      type: 'String',                         mult: '0..1', req: false, sidRef: 'Resource.resourceVersion',       description: 'Hardware / firmware version' },
        { name: 'administrativeState',  type: 'ResourceAdministrativeStateType',mult: '0..1', req: false, sidRef: 'Resource.administrativeState',   description: 'locked | unlocked | shuttingDown' },
        { name: 'lifecycleState',       type: 'ResourceLifecycleStateType',     mult: '1',    req: true,  sidRef: 'Resource.lifecycleState',        description: 'planning | installed | operating | retired' },
        { name: 'operationalState',     type: 'ResourceOperationalStateType',   mult: '0..1', req: false, sidRef: 'Resource.operationalState',      description: 'enable | disable' },
        { name: 'usageState',           type: 'ResourceUsageStateType',         mult: '0..1', req: false, sidRef: 'Resource.usageState',            description: 'idle | active | busy' },
        { name: 'resourceCharacteristic', type: 'Characteristic[]',            mult: '0..*', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'Vendor-specific and standard attributes' },
        { name: 'place',                type: 'PlaceRef',                       mult: '0..1', req: false, sidRef: 'Resource.place',                 description: 'Physical or logical location' },
      ],
    },

    NetworkElement: {
      module: 'Resource Domain',
      specRef: 'GB922 §10',
      attributes: [
        { name: 'id',                  type: 'String',                          mult: '1',    req: true,  sidRef: 'NetworkElement.id',                 description: 'Unique identifier' },
        { name: 'href',                type: 'String',                          mult: '0..1', req: false, sidRef: 'NetworkElement.href',               description: 'Canonical hypertext reference' },
        { name: 'name',                type: 'String',                          mult: '0..1', req: false, sidRef: 'NetworkElement.name',               description: 'NE hostname / label' },
        { name: 'vendorName',          type: 'String',                          mult: '0..1', req: false, sidRef: 'NetworkElement.vendorName',          description: 'Equipment manufacturer' },
        { name: 'vendorModelNumber',   type: 'String',                          mult: '0..1', req: false, sidRef: 'NetworkElement.vendorModelNumber',   description: 'Model / part number' },
        { name: 'softwareVersion',     type: 'String',                          mult: '0..1', req: false, sidRef: 'NetworkElement.softwareVersion',     description: 'Active software / firmware version' },
        { name: 'serialNumber',        type: 'String',                          mult: '0..1', req: false, sidRef: 'NetworkElement.serialNumber',        description: 'Manufacturer serial number' },
        { name: 'administrativeState', type: 'ResourceAdministrativeStateType', mult: '0..1', req: false, sidRef: 'NetworkElement.administrativeState', description: 'locked | unlocked | shuttingDown' },
        { name: 'operationalState',    type: 'ResourceOperationalStateType',    mult: '1',    req: true,  sidRef: 'NetworkElement.operationalState',    description: 'enable | disable' },
        { name: 'lifecycleState',      type: 'ResourceLifecycleStateType',      mult: '1',    req: true,  sidRef: 'NetworkElement.lifecycleState',      description: 'planning | installed | operating | retired' },
        { name: 'physicalLocation',    type: 'PlaceRef',                        mult: '0..1', req: false, sidRef: 'NetworkElement.physicalLocation',    description: 'Site, rack, or geo-coordinate' },
        { name: 'resourceCharacteristic', type: 'Characteristic[]',            mult: '0..*', req: false, sidRef: 'NetworkElement.resourceCharacteristic', description: 'KPI counters and vendor-specific attributes' },
      ],
    },

    Usage: {
      module: 'Common Business Entities',
      specRef: 'GB922 §13 / TMF635',
      attributes: [
        { name: 'id',                  type: 'String',               mult: '1',    req: true,  sidRef: 'Usage.id',                   description: 'Unique usage record identifier' },
        { name: 'href',                type: 'String',               mult: '0..1', req: false, sidRef: 'Usage.href',                 description: 'Canonical hypertext reference' },
        { name: 'usageDate',           type: 'DateTime',             mult: '1',    req: true,  sidRef: 'Usage.usageDate',            description: 'Timestamp of the usage event' },
        { name: 'description',         type: 'String',               mult: '0..1', req: false, sidRef: 'Usage.description',          description: 'Usage record description' },
        { name: 'type',                type: 'String',               mult: '0..1', req: false, sidRef: 'Usage.type',                 description: 'voice | data | sms | content | roaming' },
        { name: 'status',              type: 'UsageStatusType',      mult: '1',    req: true,  sidRef: 'Usage.status',               description: 'received | recycled | guided | rated | rejected | billed' },
        { name: 'ratingDate',          type: 'DateTime',             mult: '0..1', req: false, sidRef: 'Usage.ratingDate',           description: 'When this record was rated' },
        { name: 'billableFlag',        type: 'Boolean',              mult: '1',    req: true,  sidRef: 'Usage.billableFlag',         description: 'Whether record contributes to billing' },
        { name: 'usageCharacteristic', type: 'UsageCharacteristic[]',mult: '0..*', req: false, sidRef: 'Usage.usageCharacteristic',  description: 'Volume, duration, bytes, and domain-specific attributes' },
        { name: 'relatedParty',        type: 'RelatedParty[]',       mult: '0..*', req: false, sidRef: 'Usage.relatedParty',         description: 'Customer, subscriber, and operator parties' },
        { name: 'usageSpecification',  type: 'UsageSpecificationRef',mult: '1',    req: true,  sidRef: 'Usage.usageSpecification',   description: 'Reference to the usage specification template' },
      ],
    },

    Invoice: {
      module: 'Customer Bill Management',
      specRef: 'GB922 §12 / TMF678',
      attributes: [
        { name: 'id',              type: 'String',            mult: '1',    req: true,  sidRef: 'CustomerBill.id',             description: 'Unique invoice identifier' },
        { name: 'href',            type: 'String',            mult: '0..1', req: false, sidRef: 'CustomerBill.href',           description: 'Canonical hypertext reference' },
        { name: 'invoiceDate',     type: 'DateTime',          mult: '1',    req: true,  sidRef: 'CustomerBill.billDate',       description: 'Date invoice was generated' },
        { name: 'invoiceType',     type: 'String',            mult: '1',    req: true,  sidRef: 'CustomerBill.billType',       description: 'normal | credit | advance | correction' },
        { name: 'runType',         type: 'String',            mult: '0..1', req: false, sidRef: 'CustomerBill.runType',        description: 'onCycle | offCycle' },
        { name: 'paymentDueDate',  type: 'DateTime',          mult: '0..1', req: false, sidRef: 'CustomerBill.paymentDueDate', description: 'Payment due date' },
        { name: 'state',           type: 'InvoiceStateType',  mult: '1',    req: true,  sidRef: 'CustomerBill.state',          description: 'new | onHold | validated | sent | settled | partiallyPaid | unpaid' },
        { name: 'taxAmount',       type: 'Money',             mult: '0..1', req: false, sidRef: 'CustomerBill.taxAmount',      description: 'Total tax amount' },
        { name: 'totalAmount',     type: 'Money',             mult: '1',    req: true,  sidRef: 'CustomerBill.amountDue',      description: 'Total amount due including tax' },
        { name: 'remainingAmount', type: 'Money',             mult: '0..1', req: false, sidRef: 'CustomerBill.remainingAmount',description: 'Unpaid balance remaining' },
        { name: 'billingAccount',  type: 'BillingAccountRef', mult: '1',    req: true,  sidRef: 'CustomerBill.billingAccount', description: 'Account this invoice belongs to' },
        { name: 'appliedPayment',  type: 'AppliedPayment[]',  mult: '0..*', req: false, sidRef: 'CustomerBill.appliedPayment', description: 'Payments applied against this invoice' },
      ],
    },

    Payment: {
      module: 'Customer Bill Management',
      specRef: 'GB922 §12 / TMF676',
      attributes: [
        { name: 'id',            type: 'String',           mult: '1',    req: true,  sidRef: 'Payment.id',            description: 'Unique payment identifier' },
        { name: 'href',          type: 'String',           mult: '0..1', req: false, sidRef: 'Payment.href',          description: 'Canonical hypertext reference' },
        { name: 'description',   type: 'String',           mult: '0..1', req: false, sidRef: 'Payment.description',   description: 'Payment description or reference' },
        { name: 'amount',        type: 'Money',            mult: '1',    req: true,  sidRef: 'Payment.amount',        description: 'Payment amount and currency' },
        { name: 'status',        type: 'PaymentStatusType',mult: '1',    req: true,  sidRef: 'Payment.status',        description: 'processed | failed | reversed | pending' },
        { name: 'authorizationCode', type: 'String',       mult: '0..1', req: false, sidRef: 'Payment.authorizationCode', description: 'Acquirer authorization code' },
        { name: 'paymentDate',   type: 'DateTime',         mult: '0..1', req: false, sidRef: 'Payment.paymentDate',   description: 'When payment was processed' },
        { name: 'channel',       type: 'ChannelRef',       mult: '0..1', req: false, sidRef: 'Payment.channel',       description: 'Payment channel (card, direct debit, cash, mobile)' },
        { name: 'account',       type: 'AccountRef',       mult: '1',    req: true,  sidRef: 'Payment.account',       description: 'Billing account receiving the payment' },
        { name: 'paymentMethod', type: 'PaymentMethodRef', mult: '1',    req: true,  sidRef: 'Payment.paymentMethod', description: 'Tokenised payment instrument' },
        { name: 'payer',         type: 'RelatedParty',     mult: '1',    req: true,  sidRef: 'Payment.payer',         description: 'Party making the payment' },
      ],
    },

    TroubleTicket: {
      module: 'Engagement / Assurance',
      specRef: 'GB922 / TMF621',
      attributes: [
        { name: 'id',                      type: 'String',               mult: '1',    req: true,  sidRef: 'TroubleTicket.id',                      description: 'Unique ticket identifier' },
        { name: 'href',                    type: 'String',               mult: '0..1', req: false, sidRef: 'TroubleTicket.href',                    description: 'Canonical hypertext reference' },
        { name: 'name',                    type: 'String',               mult: '1',    req: true,  sidRef: 'TroubleTicket.name',                    description: 'Short ticket summary' },
        { name: 'description',             type: 'String',               mult: '0..1', req: false, sidRef: 'TroubleTicket.description',             description: 'Full problem description' },
        { name: 'severity',                type: 'String',               mult: '1',    req: true,  sidRef: 'TroubleTicket.severity',                description: 'critical | major | minor | cosmetic' },
        { name: 'priority',                type: 'String',               mult: '1',    req: true,  sidRef: 'TroubleTicket.priority',                description: '1 (urgent) – 4 (low)' },
        { name: 'status',                  type: 'TroubleTicketStatusType', mult: '1',req: true,  sidRef: 'TroubleTicket.status',                  description: 'new | inProgress | pending | resolved | closed | cancelled' },
        { name: 'creationDate',            type: 'DateTime',             mult: '1',    req: true,  sidRef: 'TroubleTicket.creationDate',            description: 'Ticket creation timestamp' },
        { name: 'expectedResolutionDate',  type: 'DateTime',             mult: '0..1', req: false, sidRef: 'TroubleTicket.expectedResolutionDate',  description: 'Target resolution date per SLA' },
        { name: 'closeDate',               type: 'DateTime',             mult: '0..1', req: false, sidRef: 'TroubleTicket.closeDate',               description: 'Date ticket was closed' },
        { name: 'relatedParty',            type: 'RelatedParty[]',       mult: '0..*', req: false, sidRef: 'TroubleTicket.relatedParty',            description: 'Reporters, assignees, and affected parties' },
        { name: 'note',                    type: 'Note[]',               mult: '0..*', req: false, sidRef: 'TroubleTicket.note',                    description: 'Chronological work-log entries' },
      ],
    },

    PartyInteraction: {
      module: 'Customer Domain',
      specRef: 'GB922 §6 / TMF683',
      attributes: [
        { name: 'id',              type: 'String',           mult: '1',    req: true,  sidRef: 'PartyInteraction.id',              description: 'Unique identifier' },
        { name: 'href',            type: 'String',           mult: '0..1', req: false, sidRef: 'PartyInteraction.href',            description: 'Canonical hypertext reference' },
        { name: 'interactionDate', type: 'DateTime',         mult: '1',    req: true,  sidRef: 'PartyInteraction.interactionDate', description: 'When the interaction occurred' },
        { name: 'reason',          type: 'String',           mult: '0..1', req: false, sidRef: 'PartyInteraction.reason',          description: 'Customer intent / contact reason' },
        { name: 'status',          type: 'String',           mult: '0..1', req: false, sidRef: 'PartyInteraction.status',          description: 'open | inProgress | closed' },
        { name: 'direction',       type: 'String',           mult: '0..1', req: false, sidRef: 'PartyInteraction.direction',       description: 'inbound | outbound' },
        { name: 'channel',         type: 'ChannelRef[]',     mult: '0..*', req: false, sidRef: 'PartyInteraction.channel',         description: 'Contact channels (IVR, chat, retail, app)' },
        { name: 'interactionItem', type: 'InteractionItem[]',mult: '0..*', req: false, sidRef: 'PartyInteraction.interactionItem', description: 'Products, services, or issues discussed' },
        { name: 'relatedParty',    type: 'RelatedParty[]',   mult: '1..*', req: true,  sidRef: 'PartyInteraction.relatedParty',    description: 'Customer and agent parties' },
      ],
    },

    Agreement: {
      module: 'Party Domain',
      specRef: 'GB922 §5 / TMF651',
      attributes: [
        { name: 'id',                   type: 'String',                  mult: '1',    req: true,  sidRef: 'Agreement.id',                    description: 'Unique identifier' },
        { name: 'href',                 type: 'String',                  mult: '0..1', req: false, sidRef: 'Agreement.href',                  description: 'Canonical hypertext reference' },
        { name: 'name',                 type: 'String',                  mult: '1',    req: true,  sidRef: 'Agreement.name',                  description: 'Agreement title' },
        { name: 'agreementType',        type: 'String',                  mult: '1',    req: true,  sidRef: 'Agreement.agreementType',         description: 'commercial | wholesale | roaming | consent | regulatory' },
        { name: 'documentNumber',       type: 'Integer',                 mult: '0..1', req: false, sidRef: 'Agreement.documentNumber',        description: 'Sequential reference number' },
        { name: 'initialDate',          type: 'DateTime',                mult: '0..1', req: false, sidRef: 'Agreement.initialDate',           description: 'Agreement commencement date' },
        { name: 'completionDate',       type: 'DateTime',                mult: '0..1', req: false, sidRef: 'Agreement.completionDate',        description: 'Agreement expiry date' },
        { name: 'status',               type: 'AgreementStatusType',     mult: '1',    req: true,  sidRef: 'Agreement.status',                description: 'in progress | finalized | rejected | completed | aborted' },
        { name: 'statementOfIntent',    type: 'String',                  mult: '0..1', req: false, sidRef: 'Agreement.statementOfIntent',     description: 'Commercial intent narrative' },
        { name: 'engagedParty',         type: 'RelatedParty[]',          mult: '1..*', req: true,  sidRef: 'Agreement.engagedParty',          description: 'All parties bound by the agreement' },
        { name: 'characteristic',       type: 'Characteristic[]',        mult: '0..*', req: false, sidRef: 'Agreement.characteristic',        description: 'Agreement-specific attributes (rate card, capacity…)' },
        { name: 'agreementSpecification',type: 'AgreementSpecificationRef',mult:'0..1',req: false, sidRef: 'Agreement.agreementSpecification', description: 'Template specification for this agreement type' },
      ],
    },

    FinancialAccount: {
      module: 'Customer Bill Management',
      specRef: 'GB922 §12 / TMF666',
      attributes: [
        { name: 'id',           type: 'String',                   mult: '1',    req: true,  sidRef: 'FinancialAccount.id',            description: 'Unique identifier' },
        { name: 'href',         type: 'String',                   mult: '0..1', req: false, sidRef: 'FinancialAccount.href',          description: 'Canonical hypertext reference' },
        { name: 'name',         type: 'String',                   mult: '0..1', req: false, sidRef: 'FinancialAccount.name',          description: 'Account name' },
        { name: 'accountType',  type: 'String',                   mult: '1',    req: true,  sidRef: 'FinancialAccount.accountType',   description: 'billing | settlement | credit | revenue | cost' },
        { name: 'state',        type: 'FinancialAccountStateType',mult: '1',    req: true,  sidRef: 'FinancialAccount.state',         description: 'initialized | active | closed' },
        { name: 'currency',     type: 'String',                   mult: '1',    req: true,  sidRef: 'FinancialAccount.currency',      description: 'ISO 4217 currency code' },
        { name: 'creditLimit',  type: 'Money',                    mult: '0..1', req: false, sidRef: 'FinancialAccount.creditLimit',   description: 'Credit limit on account' },
        { name: 'lastModified', type: 'DateTime',                 mult: '0..1', req: false, sidRef: 'FinancialAccount.lastModified',  description: 'Last modification timestamp' },
        { name: 'relatedParty', type: 'RelatedParty[]',           mult: '1..*', req: true,  sidRef: 'FinancialAccount.relatedParty',  description: 'Account holders and finance team' },
        { name: 'creditProfile',type: 'CreditProfile[]',          mult: '0..*', req: false, sidRef: 'FinancialAccount.creditProfile', description: 'Credit scoring and risk profile history' },
      ],
    },

    ConfigurationItem: {
      module: 'Operations / ITIL CMDB',
      specRef: 'GB922 §11 / ITIL v4',
      attributes: [
        { name: 'id',             type: 'String',       mult: '1',    req: true,  sidRef: 'ConfigurationItem.id',            description: 'Unique CI identifier' },
        { name: 'href',           type: 'String',       mult: '0..1', req: false, sidRef: 'ConfigurationItem.href',          description: 'Canonical hypertext reference' },
        { name: 'name',           type: 'String',       mult: '1',    req: true,  sidRef: 'ConfigurationItem.name',          description: 'CI display name' },
        { name: 'ciType',         type: 'String',       mult: '1',    req: true,  sidRef: 'ConfigurationItem.ciType',        description: 'server | application | network | database | service' },
        { name: 'category',       type: 'String',       mult: '0..1', req: false, sidRef: 'ConfigurationItem.category',      description: 'Functional category within CI type' },
        { name: 'version',        type: 'String',       mult: '0..1', req: false, sidRef: 'ConfigurationItem.version',       description: 'Software or hardware version' },
        { name: 'status',         type: 'CIStatusType', mult: '1',    req: true,  sidRef: 'ConfigurationItem.status',        description: 'planning | active | inactive | retired' },
        { name: 'serialNumber',   type: 'String',       mult: '0..1', req: false, sidRef: 'ConfigurationItem.serialNumber',  description: 'Physical serial number' },
        { name: 'vendor',         type: 'String',       mult: '0..1', req: false, sidRef: 'ConfigurationItem.vendor',        description: 'Manufacturer / vendor name' },
        { name: 'installDate',    type: 'DateTime',     mult: '0..1', req: false, sidRef: 'ConfigurationItem.installDate',   description: 'Date CI was installed or first detected' },
        { name: 'lastModified',   type: 'DateTime',     mult: '0..1', req: false, sidRef: 'ConfigurationItem.lastModified',  description: 'Last attribute change timestamp' },
        { name: 'relatedCI',      type: 'CIRef[]',      mult: '0..*', req: false, sidRef: 'ConfigurationItem.relatedCI',     description: 'Dependency and impact relationships' },
      ],
    },

    WorkOrder: {
      module: 'Operations Domain',
      specRef: 'GB922 §11 / TMF697',
      attributes: [
        { name: 'id',                type: 'String',           mult: '1',    req: true,  sidRef: 'WorkOrder.id',                description: 'Unique work order identifier' },
        { name: 'href',              type: 'String',           mult: '0..1', req: false, sidRef: 'WorkOrder.href',              description: 'Canonical hypertext reference' },
        { name: 'workOrderType',     type: 'String',           mult: '1',    req: true,  sidRef: 'WorkOrder.workOrderType',     description: 'installation | maintenance | fault | survey | decommission' },
        { name: 'description',       type: 'String',           mult: '0..1', req: false, sidRef: 'WorkOrder.description',       description: 'Task description and scope of work' },
        { name: 'priority',          type: 'String',           mult: '0..1', req: false, sidRef: 'WorkOrder.priority',          description: '1 (emergency) – 4 (planned)' },
        { name: 'status',            type: 'WorkOrderStateType',mult: '1',   req: true,  sidRef: 'WorkOrder.status',            description: 'created | assigned | inProgress | completed | cancelled' },
        { name: 'scheduledDate',     type: 'DateTime',         mult: '0..1', req: false, sidRef: 'WorkOrder.scheduledDate',     description: 'Planned appointment date/time' },
        { name: 'completedDate',     type: 'DateTime',         mult: '0..1', req: false, sidRef: 'WorkOrder.completedDate',     description: 'Actual completion timestamp' },
        { name: 'estimatedDuration', type: 'Duration',         mult: '0..1', req: false, sidRef: 'WorkOrder.estimatedDuration', description: 'Estimated time to complete' },
        { name: 'location',          type: 'PlaceRef',         mult: '0..1', req: false, sidRef: 'WorkOrder.location',          description: 'Site or address of field work' },
        { name: 'assignedTechnician',type: 'RelatedParty',     mult: '0..1', req: false, sidRef: 'WorkOrder.assignedTechnician',description: 'Field technician assigned' },
        { name: 'relatedAsset',      type: 'ResourceRef[]',    mult: '0..*', req: false, sidRef: 'WorkOrder.relatedAsset',      description: 'Network assets being worked on' },
      ],
    },

    Event: {
      module: 'Common Business Entities',
      specRef: 'GB922 §13 / TM Forum Event Model',
      attributes: [
        { name: 'id',                  type: 'String',   mult: '1',    req: true,  sidRef: 'Event.id',                  description: 'Unique event identifier (UUID)' },
        { name: 'href',                type: 'String',   mult: '0..1', req: false, sidRef: 'Event.href',                description: 'Canonical hypertext reference' },
        { name: 'eventType',           type: 'String',   mult: '1',    req: true,  sidRef: 'Event.eventType',           description: 'Specific event type discriminator' },
        { name: 'correlationId',       type: 'String',   mult: '0..1', req: false, sidRef: 'Event.correlationId',       description: 'Correlation identifier for event chaining' },
        { name: 'domain',              type: 'String',   mult: '0..1', req: false, sidRef: 'Event.domain',              description: 'Business domain that raised the event' },
        { name: 'title',               type: 'String',   mult: '0..1', req: false, sidRef: 'Event.title',               description: 'Human-readable event title' },
        { name: 'description',         type: 'String',   mult: '0..1', req: false, sidRef: 'Event.description',         description: 'Event description and context' },
        { name: 'priority',            type: 'String',   mult: '0..1', req: false, sidRef: 'Event.priority',            description: 'critical | high | medium | low' },
        { name: 'timeOccurred',        type: 'DateTime', mult: '1',    req: true,  sidRef: 'Event.timeOccurred',        description: 'When the event occurred' },
        { name: 'originatingSystemId', type: 'String',   mult: '0..1', req: false, sidRef: 'Event.originatingSystemId', description: 'Source system identifier' },
        { name: 'reportingSystemId',   type: 'String',   mult: '0..1', req: false, sidRef: 'Event.reportingSystemId',   description: 'System reporting the event' },
        { name: 'payload',             type: 'Object',   mult: '0..1', req: false, sidRef: 'Event.payload',             description: 'Domain-specific event payload' },
      ],
    },

    PolicyCondition: {
      module: 'Common Business Entities',
      specRef: 'GB922 §13 / TMF634',
      attributes: [
        { name: 'id',                    type: 'String',          mult: '1',    req: true,  sidRef: 'PolicyCondition.id',                    description: 'Unique identifier' },
        { name: 'href',                  type: 'String',          mult: '0..1', req: false, sidRef: 'PolicyCondition.href',                  description: 'Canonical hypertext reference' },
        { name: 'name',                  type: 'String',          mult: '1',    req: true,  sidRef: 'PolicyCondition.name',                  description: 'Policy rule name' },
        { name: 'description',           type: 'String',          mult: '0..1', req: false, sidRef: 'PolicyCondition.description',           description: 'Policy purpose and scope' },
        { name: 'status',                type: 'PolicyStateType', mult: '1',    req: true,  sidRef: 'PolicyCondition.status',                description: 'active | inactive | draft' },
        { name: 'validFor',              type: 'TimePeriod',      mult: '0..1', req: false, sidRef: 'PolicyCondition.validFor',              description: 'Effective date range for this policy' },
        { name: 'policyConditionType',   type: 'String',          mult: '0..1', req: false, sidRef: 'PolicyCondition.policyConditionType',   description: 'entitlement | rateLimit | consent | qosPolicy' },
        { name: 'constraint',            type: 'PolicyConstraint[]', mult: '0..*', req: false, sidRef: 'PolicyCondition.constraint',         description: 'Encoded constraint expressions (XACML / Rego)' },
        { name: 'specificationClause',   type: 'String',          mult: '0..1', req: false, sidRef: 'PolicyCondition.specificationClause',   description: 'Natural language policy clause' },
        { name: 'policyDecisionStrategy',type: 'String',          mult: '0..1', req: false, sidRef: 'PolicyCondition.policyDecisionStrategy',description: 'denyOverride | permitOverride | firstApplicable' },
      ],
    },

  };

  // ── Per-product declarations ─────────────────────────────────────────────────
  // entity    → key into SID_ENTITIES (required)
  // openApiRef → TMF Open API number (optional)
  // note      → product-specific context shown in UI (optional)
  // extraAttrs → additional attributes beyond the base entity (optional)
  const DATA_MODELS = {

    // ── Subscriber ──────────────────────────────────────────────────────────────
    'dp-001': { entity: 'CustomerAccount', openApiRef: 'TMF666',
      note: 'Canonical SID Customer + Individual composite. MSISDN, IMSI, KYC and tariff plan held as partyCharacteristic.',
      extraAttrs: [
        { name: 'msisdn',     type: 'String',  mult: '1',    req: true,  sidRef: 'CustomerAccount.partyCharacteristic', description: 'Mobile subscriber MSISDN (E.164)' },
        { name: 'imsi',       type: 'String',  mult: '1',    req: true,  sidRef: 'CustomerAccount.partyCharacteristic', description: 'International Mobile Subscriber Identity (15 digits)' },
        { name: 'kycStatus',  type: 'String',  mult: '0..1', req: false, sidRef: 'CustomerAccount.partyCharacteristic', description: 'Know-Your-Customer verification status' },
      ],
    },
    'dp-021': { entity: 'PartyInteraction', openApiRef: 'TMF683',
      note: 'All inbound and outbound customer touchpoints — IVR, chat, agent, retail, app — stored as InteractionItems.',
    },
    'dp-022': { entity: 'Resource', openApiRef: 'TMF639',
      note: 'Device modelled as LogicalResource with physicalResource link. GSMA IMEI TAC attributes stored as resourceCharacteristic.',
      extraAttrs: [
        { name: 'imei',          type: 'String', mult: '1',    req: true,  sidRef: 'Resource.resourceCharacteristic', description: 'IMEI (15-digit GSMA IMEI per 3GPP TS 22.016)' },
        { name: 'tacCode',       type: 'String', mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'Type Allocation Code (first 8 digits of IMEI)' },
        { name: 'deviceBrand',   type: 'String', mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'Device manufacturer from GSMA TAC DB' },
        { name: 'osType',        type: 'String', mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'Operating system: Android | iOS | KaiOS | other' },
        { name: 'linkedMsisdn',  type: 'String', mult: '0..*', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'MSISDN(s) associated with this device' },
      ],
    },
    'dp-023': { entity: 'Resource', openApiRef: 'TMF639',
      note: 'SIM modelled as LogicalResource. eSIM profiled per GSMA SGP.22 with EID and ICCID as resourceCharacteristic.',
      extraAttrs: [
        { name: 'iccid',         type: 'String', mult: '1',    req: true,  sidRef: 'Resource.resourceCharacteristic', description: 'Integrated Circuit Card ID (ICCID, 19-20 digits)' },
        { name: 'eid',           type: 'String', mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'eUICC Identifier per GSMA SGP.22' },
        { name: 'simType',       type: 'String', mult: '1',    req: true,  sidRef: 'Resource.resourceCharacteristic', description: 'physical | eSIM | softSIM' },
        { name: 'pinRetryCount', type: 'Integer',mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'Remaining PIN retry attempts' },
      ],
    },
    'dp-024': { entity: 'Event', openApiRef: null,
      note: 'Authentication events per OIDC/OAuth2. eventType discriminates login | mfa | tokenRefresh | passwordReset | lockout.',
      extraAttrs: [
        { name: 'msisdn',          type: 'String', mult: '0..1', req: false, sidRef: 'Event.payload', description: 'Subscriber MSISDN if authenticated via SIM' },
        { name: 'authMethod',      type: 'String', mult: '1',    req: true,  sidRef: 'Event.payload', description: 'password | otp | biometric | sim | certificate' },
        { name: 'riskScore',       type: 'Decimal',mult: '0..1', req: false, sidRef: 'Event.payload', description: 'Adaptive authentication risk score 0–100' },
        { name: 'deviceFingerprint',type:'String', mult: '0..1', req: false, sidRef: 'Event.payload', description: 'Hashed client device fingerprint' },
      ],
    },
    'dp-025': { entity: 'Agreement', openApiRef: 'TMF644',
      note: 'Consent record per GDPR Art.6/7. agreementType=consent; each processing purpose is a separate Agreement characteristic.',
      extraAttrs: [
        { name: 'processingPurpose', type: 'String',  mult: '1',    req: true,  sidRef: 'Agreement.characteristic', description: 'GDPR processing purpose (marketing | analytics | thirdParty…)' },
        { name: 'legalBasis',        type: 'String',  mult: '1',    req: true,  sidRef: 'Agreement.characteristic', description: 'GDPR legal basis: consent | contract | legitimateInterest | legal' },
        { name: 'withdrawalDate',    type: 'DateTime',mult: '0..1', req: false, sidRef: 'Agreement.completionDate',  description: 'Date consent was withdrawn' },
      ],
    },
    'dp-026': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'Anonymised mobility records derived from network signalling. type=geolocation; cell-to-coordinate mapping stored as usageCharacteristic.',
      extraAttrs: [
        { name: 'cellId',         type: 'String',  mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'Serving cell global ID (CGI / NCGI)' },
        { name: 'latitude',       type: 'Decimal', mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'Centroid latitude of serving cell (WGS-84)' },
        { name: 'longitude',      type: 'Decimal', mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'Centroid longitude of serving cell (WGS-84)' },
        { name: 'anonymisedId',   type: 'String',  mult: '1',    req: true,  sidRef: 'Usage.usageCharacteristic', description: 'Pseudonymous cohort identifier (GDPR Art.25)' },
      ],
    },
    'dp-027': { entity: 'TroubleTicket', openApiRef: 'TMF641',
      note: 'Customer service requests aligned with TMF641 Service Order and TMF621 Trouble Ticket. Severity driven by customer impact.',
    },
    'dp-028': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'Digital self-service behavioural events. type=digitalSelfService; usageCharacteristic captures screen, action, funnel-step.',
      extraAttrs: [
        { name: 'screenName',    type: 'String',  mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'App screen or web page name' },
        { name: 'actionType',    type: 'String',  mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'view | click | submit | abandon | error' },
        { name: 'sessionId',     type: 'String',  mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'User session identifier' },
        { name: 'funnelStep',    type: 'Integer', mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'Funnel step index (1 = entry, n = completion)' },
      ],
    },

    // ── Product ─────────────────────────────────────────────────────────────────
    'dp-002': { entity: 'ProductOffering', openApiRef: 'TMF620',
      note: 'Canonical product catalog per TMF620. ProductSpecification holds technical attributes; ProductOfferingPrice holds tariff tiers.',
    },
    'dp-029': { entity: 'ProductOffering', openApiRef: 'TMF620',
      note: 'Offering configuration layer. isBundle=true records compose child ProductOfferings linked via bundledProductOffering.',
    },
    'dp-030': { entity: 'ProductOrder', openApiRef: 'TMF622',
      note: 'End-to-end order lifecycle. Each ProductOrderItem decomposes into ServiceOrder (TMF641) and ResourceOrder (TMF652) downstream.',
    },
    'dp-031': { entity: 'Promotion', openApiRef: 'TMF671',
      note: 'Bundle and promotion registry. PromotionPattern encodes eligibility criteria (tariff plan, tenure, segment) and reward type.',
      extraAttrs: [
        { name: 'discountType',     type: 'String',  mult: '0..1', req: false, sidRef: 'Promotion.pattern', description: 'percentage | fixedAmount | freeUnit | productGift' },
        { name: 'eligibilityRule',  type: 'String',  mult: '0..*', req: false, sidRef: 'Promotion.pattern', description: 'Encoded eligibility expression (DMN / FEEL)' },
        { name: 'campaignId',       type: 'String',  mult: '0..1', req: false, sidRef: 'Promotion.pattern', description: 'Parent marketing campaign reference' },
      ],
    },
    'dp-032': { entity: 'Event', openApiRef: 'TMF688',
      note: 'Immutable product lifecycle event log. eventType ∈ {ProductOfferingCreated, ProductOfferingStatusChanged, ProductOfferingRetired}.',
    },
    'dp-033': { entity: 'ProductOffering', openApiRef: 'TMF620',
      note: 'Tariff and pricing repository. ProductOfferingPrice holds PricingLogicAlgorithm references for complex tiered and dynamic pricing.',
      extraAttrs: [
        { name: 'priceType',         type: 'String', mult: '1',    req: true,  sidRef: 'ProductOfferingPrice.priceType',   description: 'recurring | oneTime | usage | allowance' },
        { name: 'recurringChargePeriod', type: 'String', mult: '0..1', req: false, sidRef: 'ProductOfferingPrice.recurringChargePeriod', description: 'monthly | daily | annual' },
        { name: 'pricingLogicAlgorithm', type: 'PricingLogicAlgorithmRef', mult: '0..1', req: false, sidRef: 'ProductOfferingPrice.pricingLogicAlgorithm', description: 'Complex pricing engine reference' },
      ],
    },
    'dp-034': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'Product performance KPIs aggregated as usage records. type=productKPI; usageCharacteristic carries ARPU, subscriberCount, churnRate.',
    },
    'dp-035': { entity: 'PolicyCondition', openApiRef: 'TMF634',
      note: 'Entitlement registry. policyConditionType=entitlement; constraints encode data allowance, QoS tier, roaming zones per product.',
    },
    'dp-036': { entity: 'ProductOffering', openApiRef: 'TMF620',
      note: 'Recommendation engine output. Recommended offerings serialised as ProductOffering references with confidence score characteristic.',
      extraAttrs: [
        { name: 'confidenceScore', type: 'Decimal', mult: '1',    req: true,  sidRef: 'ProductOffering.productOfferingCharacteristic', description: 'ML model confidence score 0.0–1.0' },
        { name: 'recommendedFor',  type: 'String',  mult: '1',    req: true,  sidRef: 'ProductOffering.productOfferingCharacteristic', description: 'MSISDN or segment identifier targeted' },
        { name: 'modelVersion',    type: 'String',  mult: '0..1', req: false, sidRef: 'ProductOffering.productOfferingCharacteristic', description: 'ML model version that generated this score' },
      ],
    },

    // ── Service ─────────────────────────────────────────────────────────────────
    'dp-006': { entity: 'Service', openApiRef: 'TMF638',
      note: 'Product inventory instances: each active subscription maps to a Service (productInventory) linked to a ProductOrder.',
    },
    'dp-007': { entity: 'Service', openApiRef: 'TMF638',
      note: 'Service inventory per TMF638. serviceCharacteristic carries MSISDN, APN, QoS class, network slice (S-NSSAI) assignments.',
    },
    'dp-037': { entity: 'Service', openApiRef: 'TMF640',
      note: 'Service activation events. State transitions per TMF640 lifecycle: designed → reserved → active → terminated.',
      extraAttrs: [
        { name: 'activationOutcome', type: 'String',   mult: '1',    req: true,  sidRef: 'Service.serviceCharacteristic', description: 'success | failed | partial | rollback' },
        { name: 'provisioningSystem',type: 'String',   mult: '0..1', req: false, sidRef: 'Service.serviceCharacteristic', description: 'OSS provisioning system identifier' },
        { name: 'activationDuration',type: 'Duration', mult: '0..1', req: false, sidRef: 'Service.serviceCharacteristic', description: 'End-to-end activation time (SLA gate)' },
      ],
    },
    'dp-038': { entity: 'ServiceProblem', openApiRef: 'TMF656',
      note: 'Service problem records per TMF656. affectedService links to impacted Service instances; associatedSLA flags SLA at risk.',
    },
    'dp-039': { entity: 'ServiceLevelAgreement', openApiRef: 'TMF623',
      note: 'SLA definitions and real-time compliance. SLARule encodes KPI thresholds (availability %, MTTR, latency ms).',
    },
    'dp-040': { entity: 'Service', openApiRef: 'TMF638',
      note: 'VoLTE/IMS service instances. serviceCharacteristic captures SIP URI, codec negotiated, IMS P-CSCF address, VoWiFi preference.',
      extraAttrs: [
        { name: 'sipUri',          type: 'String', mult: '1',    req: true,  sidRef: 'Service.serviceCharacteristic', description: 'SIP URI for this IMS subscriber (3GPP TS 23.003)' },
        { name: 'voiceCodec',      type: 'String', mult: '0..1', req: false, sidRef: 'Service.serviceCharacteristic', description: 'EVS | AMR-WB | AMR-NB codec preference' },
        { name: 'imsRegistration', type: 'String', mult: '1',    req: true,  sidRef: 'Service.serviceCharacteristic', description: 'registered | deregistered | emergency' },
      ],
    },
    'dp-041': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'VAS usage records. type=vas; usageCharacteristic discriminates SMS / MMS / content / DCB service identifiers and volume.',
    },
    'dp-042': { entity: 'Service', openApiRef: 'TMF681',
      note: 'IoT/M2M service instances per TMF681 IoT Device Management. serviceCharacteristic holds ICCID, APN, device EUI, connectivity plan.',
      extraAttrs: [
        { name: 'deviceEUI',       type: 'String', mult: '0..1', req: false, sidRef: 'Service.serviceCharacteristic', description: 'LoRaWAN / NB-IoT device EUI (64-bit)' },
        { name: 'connectivityPlan',type: 'String', mult: '1',    req: true,  sidRef: 'Service.serviceCharacteristic', description: 'IoT connectivity plan identifier' },
        { name: 'dataUsageMB',     type: 'Decimal',mult: '0..1', req: false, sidRef: 'Service.serviceCharacteristic', description: 'Data consumed in current cycle (MB)' },
      ],
    },
    'dp-043': { entity: 'Service', openApiRef: 'TMF638',
      note: 'Fixed broadband service instances. serviceCharacteristic carries ONT serial, line profile, sync rate, CPE MAC.',
      extraAttrs: [
        { name: 'ontSerial',       type: 'String',  mult: '0..1', req: false, sidRef: 'Service.serviceCharacteristic', description: 'Optical Network Terminal serial number' },
        { name: 'downloadSpeedMbps',type:'Integer', mult: '1',    req: true,  sidRef: 'Service.serviceCharacteristic', description: 'Contracted download speed (Mbps)' },
        { name: 'lineProfile',     type: 'String',  mult: '0..1', req: false, sidRef: 'Service.serviceCharacteristic', description: 'GPON / xDSL line profile identifier' },
      ],
    },
    'dp-044': { entity: 'Service', openApiRef: 'TMF638',
      note: 'Enterprise managed service instances. serviceCharacteristic carries CE router details, MPLS VPN ID, SD-WAN policy, SLA tier.',
      extraAttrs: [
        { name: 'vlanId',          type: 'Integer', mult: '0..1', req: false, sidRef: 'Service.serviceCharacteristic', description: 'Customer VLAN identifier' },
        { name: 'mplsVpnId',       type: 'String',  mult: '0..1', req: false, sidRef: 'Service.serviceCharacteristic', description: 'MPLS L3VPN route distinguisher' },
        { name: 'contractedBandwidthMbps', type: 'Integer', mult: '1', req: true, sidRef: 'Service.serviceCharacteristic', description: 'Contracted access bandwidth (Mbps)' },
      ],
    },

    // ── Network ─────────────────────────────────────────────────────────────────
    'dp-003': { entity: 'Resource', openApiRef: 'TMF639',
      note: 'Network resource inventory per TMF639. ResourceSpecification defines NE types; Resource instances link to physical sites.',
    },
    'dp-008': { entity: 'NetworkElement', openApiRef: 'TMF642',
      note: 'RAN and core KPI counters per 3GPP TS 28.552 (5G) / 32.401 (LTE). resourceCharacteristic holds PM counter families.',
    },
    'dp-009': { entity: 'Event', openApiRef: 'TMF642',
      note: 'Alarm and event management per TMF642. eventType maps to 3GPP alarm categories: communicationsAlarm | processingErrorAlarm.',
      extraAttrs: [
        { name: 'alarmType',         type: 'String',  mult: '1',    req: true,  sidRef: 'Event.payload', description: '3GPP alarm type per X.733 (communicationsAlarm | qualityOfServiceAlarm…)' },
        { name: 'probableCause',     type: 'String',  mult: '0..1', req: false, sidRef: 'Event.payload', description: 'ITU-T X.733 probable cause code' },
        { name: 'perceivedSeverity', type: 'String',  mult: '1',    req: true,  sidRef: 'Event.payload', description: 'critical | major | minor | warning | indeterminate | cleared' },
        { name: 'managedObjectClass',type: 'String',  mult: '0..1', req: false, sidRef: 'Event.payload', description: 'Network managed object class (3GPP DN)' },
      ],
    },
    'dp-012': { entity: 'NetworkElement', openApiRef: 'TMF642',
      note: 'RAN cell / BTS performance. resourceCharacteristic holds 3GPP TS 28.552 NR-NRCellDU and LTE EUtranCellFDD/TDD PM counters.',
      extraAttrs: [
        { name: 'cellGlobalId',    type: 'String',  mult: '1',    req: true,  sidRef: 'NetworkElement.resourceCharacteristic', description: 'NCI (NR) or ECGI (LTE) cell global identifier' },
        { name: 'arfcn',           type: 'Integer', mult: '0..1', req: false, sidRef: 'NetworkElement.resourceCharacteristic', description: 'Absolute Radio Frequency Channel Number' },
        { name: 'pci',             type: 'Integer', mult: '0..1', req: false, sidRef: 'NetworkElement.resourceCharacteristic', description: 'Physical Cell Identity (0–1007)' },
        { name: 'transmitPowerDbm',type: 'Decimal', mult: '0..1', req: false, sidRef: 'NetworkElement.resourceCharacteristic', description: 'Cell transmit power (dBm)' },
      ],
    },
    'dp-045': { entity: 'Event', openApiRef: null,
      note: 'SS7/Diameter signalling decoded events. eventType maps to MAP/CAMEL operation codes and Diameter command codes (3GPP TS 29.002).',
      extraAttrs: [
        { name: 'protocolFamily',  type: 'String', mult: '1',    req: true,  sidRef: 'Event.payload', description: 'SS7 | Diameter | GTP-C | SIP' },
        { name: 'commandCode',     type: 'Integer',mult: '0..1', req: false, sidRef: 'Event.payload', description: 'Diameter command code or SS7 operation code' },
        { name: 'originHost',      type: 'String', mult: '0..1', req: false, sidRef: 'Event.payload', description: 'Diameter Origin-Host AVP / SS7 PC' },
        { name: 'destinationHost', type: 'String', mult: '0..1', req: false, sidRef: 'Event.payload', description: 'Diameter Destination-Host AVP / SS7 DPC' },
      ],
    },
    'dp-046': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'IP flow records (IPFIX RFC 7011 / NetFlow v9 RFC 3954). type=ipFlow; usageCharacteristic holds 5-tuple and byte/packet counters.',
      extraAttrs: [
        { name: 'sourceAddress',   type: 'String',  mult: '1',    req: true,  sidRef: 'Usage.usageCharacteristic', description: 'Source IP address (IPv4/IPv6)' },
        { name: 'destinationAddress',type:'String', mult: '1',    req: true,  sidRef: 'Usage.usageCharacteristic', description: 'Destination IP address (IPv4/IPv6)' },
        { name: 'protocol',        type: 'Integer', mult: '1',    req: true,  sidRef: 'Usage.usageCharacteristic', description: 'IP protocol number (6=TCP, 17=UDP, 132=SCTP)' },
        { name: 'octetCount',      type: 'Long',    mult: '1',    req: true,  sidRef: 'Usage.usageCharacteristic', description: 'Total bytes transferred in flow' },
        { name: 'appId',           type: 'String',  mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'Application classification from DPI (IANA / IETF)' },
      ],
    },
    'dp-047': { entity: 'Resource', openApiRef: 'TMF639',
      note: 'Optical and microwave transport network data. resourceType=transmissionLink; resourceCharacteristic holds OTN layer rates and BER.',
      extraAttrs: [
        { name: 'linkCapacityGbps', type: 'Decimal', mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'Nominal link capacity (Gbps)' },
        { name: 'utilizationPct',   type: 'Decimal', mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'Current utilisation percentage' },
        { name: 'otdmLayer',        type: 'String',  mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'OTN layer (OTU1/2/3/4) or SDH frame rate' },
      ],
    },
    'dp-048': { entity: 'Resource', openApiRef: null,
      note: '5G Network Slice per 3GPP TS 28.530. resourceType=networkSlice; S-NSSAI (SST+SD) and NSI-ID stored as resourceCharacteristic.',
      extraAttrs: [
        { name: 'sst',             type: 'Integer', mult: '1',    req: true,  sidRef: 'Resource.resourceCharacteristic', description: 'Slice/Service Type (1=eMBB, 2=URLLC, 3=MIoT)' },
        { name: 'sd',              type: 'String',  mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'Slice Differentiator (24-bit hex, optional)' },
        { name: 'nsiId',           type: 'String',  mult: '1',    req: true,  sidRef: 'Resource.resourceCharacteristic', description: 'Network Slice Instance ID (3GPP TS 28.530)' },
        { name: 'maxUeCount',      type: 'Integer', mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'Maximum concurrent UEs on this slice' },
      ],
    },
    'dp-049': { entity: 'Resource', openApiRef: 'TMF639',
      note: 'Physical and logical network topology per TMF639 ResourceInventory. Nodes (TopologyHub) and links (TopologyLink) with geo-attributes.',
      extraAttrs: [
        { name: 'latitude',        type: 'Decimal', mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'Site latitude (WGS-84)' },
        { name: 'longitude',       type: 'Decimal', mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'Site longitude (WGS-84)' },
        { name: 'topologyLayer',   type: 'String',  mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'IP | transport | RAN | access | core' },
      ],
    },
    'dp-050': { entity: 'Resource', openApiRef: 'TMF639',
      note: 'Network configuration repository. resourceType=configuration; YANG data models stored as resourceCharacteristic (JSON-encoded).',
      extraAttrs: [
        { name: 'yangModel',       type: 'String',  mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'YANG module name (RFC 6020)' },
        { name: 'configVersion',   type: 'String',  mult: '1',    req: true,  sidRef: 'Resource.resourceCharacteristic', description: 'Git commit SHA of this configuration snapshot' },
        { name: 'complianceStatus',type: 'String',  mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'compliant | drifted | remediated' },
      ],
    },
    'dp-051': { entity: 'Resource', openApiRef: null,
      note: 'Spectrum and RF planning data. resourceType=frequencyBand; resourceCharacteristic captures licence conditions and propagation parameters.',
      extraAttrs: [
        { name: 'frequencyBandMHz', type: 'String',  mult: '1',    req: true,  sidRef: 'Resource.resourceCharacteristic', description: 'Centre frequency and bandwidth (e.g. 3500 MHz / 100 MHz)' },
        { name: 'licenceNumber',    type: 'String',  mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'National regulator spectrum licence number' },
        { name: 'technology',       type: 'String',  mult: '1',    req: true,  sidRef: 'Resource.resourceCharacteristic', description: 'LTE | NR | NR-U | Wi-Fi | CBRS' },
        { name: 'eirpDbm',          type: 'Decimal', mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'Max EIRP per regulatory licence (dBm)' },
      ],
    },
    'dp-052': { entity: 'Event', openApiRef: 'TMF688',
      note: 'OSS/BSS integration events per TM Forum Event Model. eventType follows TMF688 naming: {EntityType}{Action}Notification.',
    },
    'dp-053': { entity: 'Event', openApiRef: null,
      note: 'Network security SIEM events. eventType ∈ {DDoSDetected, FirewallDeny, IntrusionAttempt, AnomalousFlow}. Feeds SOC playbooks.',
      extraAttrs: [
        { name: 'sourceIp',        type: 'String',  mult: '0..1', req: false, sidRef: 'Event.payload', description: 'Attack source IP address' },
        { name: 'attackVector',    type: 'String',  mult: '0..1', req: false, sidRef: 'Event.payload', description: 'CVE vector string (CVSS v3.1)' },
        { name: 'ruleId',          type: 'String',  mult: '0..1', req: false, sidRef: 'Event.payload', description: 'SIEM detection rule identifier' },
        { name: 'mitreTactic',     type: 'String',  mult: '0..1', req: false, sidRef: 'Event.payload', description: 'MITRE ATT&CK tactic (e.g. TA0001 Initial Access)' },
      ],
    },
    'dp-054': { entity: 'Resource', openApiRef: null,
      note: 'MEC edge node resources per ETSI MEC GS 003. resourceType=mecHost; resourceCharacteristic captures vCPU, RAM, GPU, latency-zone.',
      extraAttrs: [
        { name: 'mecHostId',       type: 'String',  mult: '1',    req: true,  sidRef: 'Resource.resourceCharacteristic', description: 'ETSI MEC host identifier' },
        { name: 'availableVcpu',   type: 'Integer', mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'Available vCPU capacity' },
        { name: 'latencyZone',     type: 'String',  mult: '0..1', req: false, sidRef: 'Resource.resourceCharacteristic', description: 'Ultra-low (<5ms) | low (<20ms) | standard' },
      ],
    },

    // ── Analytics ───────────────────────────────────────────────────────────────
    'dp-010': { entity: 'CustomerAccount', openApiRef: 'TMF666',
      note: 'Customer 360 golden record. Aggregates CustomerAccount, Individual, Usage and CEM signals into a single analytical entity.',
    },
    'dp-015': { entity: 'CustomerAccount', openApiRef: 'TMF666',
      note: 'Segmentation output. Segment membership stored as partyCharacteristic (segmentCode, segmentScore, segmentVersion).',
      extraAttrs: [
        { name: 'segmentCode',     type: 'String',  mult: '1',    req: true,  sidRef: 'CustomerAccount.partyCharacteristic', description: 'Segment identifier from clustering model' },
        { name: 'segmentScore',    type: 'Decimal', mult: '0..1', req: false, sidRef: 'CustomerAccount.partyCharacteristic', description: 'Cluster membership confidence score 0–1' },
      ],
    },
    'dp-016': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'CEM analytics. type=cemQualityEvent; usageCharacteristic carries MOS, throughput, latency, and handover failure indicator.',
    },
    'dp-017': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'Churn prediction scores. type=churnPropensity; usageCharacteristic carries churnProbability, churnReason, retentionOffer.',
    },
    'dp-018': { entity: 'FinancialAccount', openApiRef: 'TMF666',
      note: 'Revenue assurance financial account. accountType=revenueAssurance; creditProfile holds leakage detection findings.',
    },
    'dp-019': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'NPS and CX analytics. type=npsEvent; usageCharacteristic carries npsScore, verbatimFeedback, surveyChannel.',
    },
    'dp-020': { entity: 'NetworkElement', openApiRef: 'TMF642',
      note: '5G coverage planning data. resourceCharacteristic carries predicted coverage (dBm) per geo-tile and deployment scenario.',
    },
    'dp-055': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'Propensity-to-buy scores. type=propensityScore; usageCharacteristic carries propensityType, score, modelVersion, decile.',
      extraAttrs: [
        { name: 'propensityType',  type: 'String',  mult: '1',    req: true,  sidRef: 'Usage.usageCharacteristic', description: 'upgrade | crossSell | churn | winBack' },
        { name: 'score',           type: 'Decimal', mult: '1',    req: true,  sidRef: 'Usage.usageCharacteristic', description: 'Propensity score 0.0–1.0' },
        { name: 'decile',          type: 'Integer', mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'Score decile (1=highest propensity)' },
        { name: 'modelVersion',    type: 'String',  mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'ML model version used for scoring' },
      ],
    },
    'dp-056': { entity: 'Event', openApiRef: 'TMF642',
      note: 'Network anomaly detection alerts. eventType=NetworkAnomalyDetected; payload carries detector model, anomaly score, affected NE.',
      extraAttrs: [
        { name: 'anomalyScore',    type: 'Decimal', mult: '1',    req: true,  sidRef: 'Event.payload', description: 'Isolation forest anomaly score (higher = more anomalous)' },
        { name: 'affectedKpi',     type: 'String',  mult: '1',    req: true,  sidRef: 'Event.payload', description: 'KPI exhibiting anomalous behaviour' },
        { name: 'detectorModel',   type: 'String',  mult: '0..1', req: false, sidRef: 'Event.payload', description: 'ML model name and version' },
      ],
    },
    'dp-057': { entity: 'FinancialAccount', openApiRef: 'TMF666',
      note: 'Customer lifetime value. accountType=clv; creditProfile stores CLV amount, prediction interval, and model metadata.',
      extraAttrs: [
        { name: 'historicalClv',   type: 'Money',   mult: '0..1', req: false, sidRef: 'FinancialAccount.creditProfile', description: 'Realised CLV to date' },
        { name: 'predictedClv12m', type: 'Money',   mult: '0..1', req: false, sidRef: 'FinancialAccount.creditProfile', description: 'Predicted CLV over next 12 months' },
        { name: 'clvDecile',       type: 'Integer', mult: '0..1', req: false, sidRef: 'FinancialAccount.creditProfile', description: 'CLV decile (1=highest value)' },
      ],
    },
    'dp-058': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'Social media sentiment. type=sentimentScore; usageCharacteristic carries platform, sentiment class, score, and mention volume.',
      extraAttrs: [
        { name: 'platform',        type: 'String',  mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'twitter | facebook | instagram | appStore | playStore' },
        { name: 'sentimentClass',  type: 'String',  mult: '1',    req: true,  sidRef: 'Usage.usageCharacteristic', description: 'positive | neutral | negative' },
        { name: 'sentimentScore',  type: 'Decimal', mult: '1',    req: true,  sidRef: 'Usage.usageCharacteristic', description: 'NLP sentiment score -1.0 (neg) to +1.0 (pos)' },
      ],
    },
    'dp-059': { entity: 'NetworkElement', openApiRef: 'TMF642',
      note: 'Predictive maintenance. resourceCharacteristic carries failureProbability, timeToFailure, maintenanceUrgency per NE.',
      extraAttrs: [
        { name: 'failureProbability', type: 'Decimal', mult: '1',    req: true,  sidRef: 'NetworkElement.resourceCharacteristic', description: 'Predicted failure probability 0–1 (next 30 days)' },
        { name: 'timeToFailureDays',  type: 'Integer', mult: '0..1', req: false, sidRef: 'NetworkElement.resourceCharacteristic', description: 'Estimated days until failure' },
        { name: 'maintenanceUrgency', type: 'String',  mult: '1',    req: true,  sidRef: 'NetworkElement.resourceCharacteristic', description: 'immediate | scheduled | monitor' },
      ],
    },
    'dp-060': { entity: 'Event', openApiRef: 'TMF688',
      note: 'Real-time CEP analytics. eventType=ComplexEventDetected; payload carries pattern name, matched events, and derived KPI.',
      extraAttrs: [
        { name: 'patternName',     type: 'String',  mult: '1',    req: true,  sidRef: 'Event.payload', description: 'CEP pattern that triggered this event' },
        { name: 'windowSizeMs',    type: 'Long',    mult: '0..1', req: false, sidRef: 'Event.payload', description: 'Aggregation window size in milliseconds' },
        { name: 'matchedEventIds', type: 'String[]',mult: '0..*', req: false, sidRef: 'Event.payload', description: 'Source event IDs that matched the pattern' },
      ],
    },
    'dp-061': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'Market share analytics. type=marketShareMetric; usageCharacteristic carries segment, portInCount, portOutCount, sharePercent.',
    },
    'dp-062': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'Campaign performance. type=campaignKPI; usageCharacteristic carries campaignId, channel, reach, conversions, uplift, ROI.',
      extraAttrs: [
        { name: 'campaignId',      type: 'String',  mult: '1',    req: true,  sidRef: 'Usage.usageCharacteristic', description: 'Marketing campaign identifier' },
        { name: 'conversionRate',  type: 'Decimal', mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'Conversions / reach (0–1)' },
        { name: 'roi',             type: 'Decimal', mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'Return on investment ratio' },
      ],
    },

    // ── Finance ─────────────────────────────────────────────────────────────────
    'dp-004': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'CDR mediation output per 3GPP TS 32.297. type=voice|data|sms; usageCharacteristic holds all 3GPP CDR fields post-mediation.',
    },
    'dp-005': { entity: 'CustomerAccount', openApiRef: 'TMF666',
      note: 'Customer billing profile. accountType=postpaid|prepaid; billingCycleSpecification, paymentMethod and creditLimit are key attributes.',
    },
    'dp-013': { entity: 'FinancialAccount', openApiRef: 'TMF666',
      note: 'Revenue assurance. accountType=revenueAssurance; reconciliation discrepancies stored as creditProfile findings with leakage amount.',
    },
    'dp-063': { entity: 'Invoice', openApiRef: 'TMF678',
      note: 'Customer bill per TMF678. appliedPayment links capture all payments; billableUsage sub-resource references rated CDRs.',
    },
    'dp-064': { entity: 'Payment', openApiRef: 'TMF676',
      note: 'Payment transactions. PCI-DSS compliant: card PAN replaced by token in paymentMethod; authorizationCode from acquirer.',
    },
    'dp-065': { entity: 'FinancialAccount', openApiRef: 'TMF666',
      note: 'Credit risk scoring. accountType=creditRisk; creditProfile holds bureau score, internal score, credit decision, and IFRS 9 ECL.',
      extraAttrs: [
        { name: 'bureauScore',     type: 'Integer', mult: '0..1', req: false, sidRef: 'FinancialAccount.creditProfile', description: 'External credit bureau score' },
        { name: 'internalScore',   type: 'Integer', mult: '0..1', req: false, sidRef: 'FinancialAccount.creditProfile', description: 'Internal behavioural credit score' },
        { name: 'creditDecision',  type: 'String',  mult: '1',    req: true,  sidRef: 'FinancialAccount.creditProfile', description: 'approve | decline | refer | limit' },
        { name: 'eclProbability',  type: 'Decimal', mult: '0..1', req: false, sidRef: 'FinancialAccount.creditProfile', description: 'IFRS 9 Expected Credit Loss probability' },
      ],
    },
    'dp-066': { entity: 'Agreement', openApiRef: null,
      note: 'Regulatory reporting data. agreementType=regulatoryObligation; characteristic holds NRA submission period and metric values.',
    },
    'dp-067': { entity: 'FinancialAccount', openApiRef: 'TMF666',
      note: 'Financial reconciliation. accountType=reconciliation; creditProfile stores discrepancy findings (type, amount, root cause).',
    },
    'dp-068': { entity: 'Agreement', openApiRef: null,
      note: 'Interconnect cost management. agreementType=wholesale; characteristic holds GSMA TAP3 settlement rates and cost-per-unit.',
      extraAttrs: [
        { name: 'tap3FileRef',      type: 'String',  mult: '0..1', req: false, sidRef: 'Agreement.characteristic', description: 'GSMA TAP3 file identifier (TD.57)' },
        { name: 'settlementPeriod', type: 'TimePeriod', mult: '1', req: true,  sidRef: 'Agreement.characteristic', description: 'Settlement billing period' },
        { name: 'costPerMinute',    type: 'Money',   mult: '0..1', req: false, sidRef: 'Agreement.characteristic', description: 'Interconnect rate per minute' },
      ],
    },
    'dp-069': { entity: 'FinancialAccount', openApiRef: 'TMF666',
      note: 'Cost allocation and profitability P&L. accountType=costAllocation; creditProfile stores ABC cost drivers and allocated amounts.',
    },
    'dp-070': { entity: 'FinancialAccount', openApiRef: 'TMF666',
      note: 'Dunning and debt management. accountType=dunning; creditProfile holds dunning stage, days-overdue, collection action, write-off flag.',
      extraAttrs: [
        { name: 'dunningStage',     type: 'String',  mult: '1',    req: true,  sidRef: 'FinancialAccount.creditProfile', description: 'reminder1 | reminder2 | suspension | collections | writeOff' },
        { name: 'daysOverdue',      type: 'Integer', mult: '1',    req: true,  sidRef: 'FinancialAccount.creditProfile', description: 'Number of days past payment due date' },
        { name: 'outstandingAmount',type: 'Money',   mult: '1',    req: true,  sidRef: 'FinancialAccount.creditProfile', description: 'Total outstanding debt amount' },
      ],
    },

    // ── Partner ─────────────────────────────────────────────────────────────────
    'dp-014': { entity: 'Agreement', openApiRef: 'TMF651',
      note: 'Roaming and interconnect agreements. agreementType=roaming; characteristic captures IR.21 data exchange and TAP3 settlement terms.',
    },
    'dp-071': { entity: 'Agreement', openApiRef: 'TMF702',
      note: 'MVNO partner agreement. agreementType=mvno; characteristic holds MVNO rate card, coverage perimeter, and QoS commitments.',
      extraAttrs: [
        { name: 'mvnoType',         type: 'String',  mult: '1',    req: true,  sidRef: 'Agreement.characteristic', description: 'full | light | enhanced | virtual' },
        { name: 'subscriberCap',    type: 'Integer', mult: '0..1', req: false, sidRef: 'Agreement.characteristic', description: 'Maximum MVNO subscriber count under this agreement' },
      ],
    },
    'dp-072': { entity: 'Agreement', openApiRef: null,
      note: 'Content provider revenue share. agreementType=revenueShare; characteristic holds split percentage, minimum guarantee, and payment terms.',
      extraAttrs: [
        { name: 'revenueSharePct',  type: 'Decimal', mult: '1',    req: true,  sidRef: 'Agreement.characteristic', description: 'Operator revenue share percentage (0–100)' },
        { name: 'minimumGuarantee',type: 'Money',   mult: '0..1', req: false, sidRef: 'Agreement.characteristic', description: 'Monthly minimum guarantee to content partner' },
      ],
    },
    'dp-073': { entity: 'PolicyCondition', openApiRef: 'TMF732',
      note: 'API partner gateway events. policyConditionType=rateLimit; constraint encodes quota, rate limit, and monetisation tier per API key.',
      extraAttrs: [
        { name: 'apiProductId',     type: 'String',  mult: '1',    req: true,  sidRef: 'PolicyCondition.constraint', description: 'API product identifier in developer portal' },
        { name: 'quotaLimit',       type: 'Long',    mult: '0..1', req: false, sidRef: 'PolicyCondition.constraint', description: 'API call quota per period' },
        { name: 'quotaPeriod',      type: 'String',  mult: '0..1', req: false, sidRef: 'PolicyCondition.constraint', description: 'second | minute | hour | day | month' },
      ],
    },
    'dp-074': { entity: 'Agreement', openApiRef: null,
      note: 'Wholesale capacity management. agreementType=wholesale; characteristic holds contracted bandwidth, IRU terms, and utilisation thresholds.',
    },
    'dp-075': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'Interconnect quality analytics. type=interconnectQuality; usageCharacteristic carries ASR, ACD, NER per route and partner.',
      extraAttrs: [
        { name: 'asr',             type: 'Decimal', mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'Answer Seizure Ratio (0–1)' },
        { name: 'acd',             type: 'Decimal', mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'Average Call Duration (seconds)' },
        { name: 'ner',             type: 'Decimal', mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'Network Effectiveness Ratio (0–1)' },
        { name: 'partnerCarrier',  type: 'String',  mult: '1',    req: true,  sidRef: 'Usage.usageCharacteristic', description: 'Interconnect partner carrier identifier' },
      ],
    },
    'dp-076': { entity: 'Agreement', openApiRef: null,
      note: 'Regulatory compliance and audit. agreementType=regulatoryCompliance; characteristic holds control status, evidence references, and audit findings.',
    },

    // ── Operations ──────────────────────────────────────────────────────────────
    'dp-011': { entity: 'ServiceLevelAgreement', openApiRef: 'TMF623',
      note: 'Service quality and SLA monitoring. SLARule thresholds per KPI class; real-time compliance evaluated per measurement window.',
    },
    'dp-077': { entity: 'WorkOrder', openApiRef: 'TMF697',
      note: 'Field force work orders. workOrderType ∈ {installation, maintenance, faultClearance, survey}. GPS location tracked as PlaceRef.',
    },
    'dp-078': { entity: 'TroubleTicket', openApiRef: 'TMF621',
      note: 'Customer complaint management. ticketType=customerComplaint; regulatory escalation tracked via relatedParty (ombudsman role).',
    },
    'dp-079': { entity: 'ConfigurationItem', openApiRef: null,
      note: 'Change management events. ciType=changeRecord; status lifecycle maps to ITIL Change Enablement: logged → approved → implemented → reviewed.',
      extraAttrs: [
        { name: 'changeType',      type: 'String',  mult: '1',    req: true,  sidRef: 'ConfigurationItem.category', description: 'normal | emergency | standard' },
        { name: 'cabDecision',     type: 'String',  mult: '0..1', req: false, sidRef: 'ConfigurationItem.category', description: 'approved | rejected | deferred' },
        { name: 'maintenanceWindow',type:'TimePeriod',mult:'0..1',req: false, sidRef: 'ConfigurationItem.category', description: 'Approved implementation maintenance window' },
      ],
    },
    'dp-080': { entity: 'ConfigurationItem', openApiRef: null,
      note: 'IT asset and configuration management (CMDB). relatedCI captures dependency and impact relationships for change and incident management.',
    },
    'dp-081': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'Workforce analytics. type=hrMetric; usageCharacteristic carries headcount, attritionRate, productivityScore (anonymised).',
    },
    'dp-082': { entity: 'Usage', openApiRef: 'TMF635',
      note: 'Energy consumption. type=energyUsage; usageCharacteristic holds kWh, CO2eKg, energySourceType per site (GSMA Green Future targets).',
      extraAttrs: [
        { name: 'siteType',        type: 'String',  mult: '1',    req: true,  sidRef: 'Usage.usageCharacteristic', description: 'bts | datacenter | office | warehouse' },
        { name: 'energyKwh',       type: 'Decimal', mult: '1',    req: true,  sidRef: 'Usage.usageCharacteristic', description: 'Energy consumed in kilowatt-hours' },
        { name: 'co2eKg',          type: 'Decimal', mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'CO₂-equivalent emissions (kg)' },
        { name: 'renewablePct',    type: 'Decimal', mult: '0..1', req: false, sidRef: 'Usage.usageCharacteristic', description: 'Percentage from renewable energy sources' },
      ],
    },
    'dp-083': { entity: 'TroubleTicket', openApiRef: 'TMF656',
      note: 'Incident and problem management per TMF656 and ITIL v4. ticketType=networkIncident; severity auto-classified from correlated alarm count.',
    },
  };

  // ── Public API ───────────────────────────────────────────────────────────────
  function get(productId) {
    const decl = DATA_MODELS[productId];
    if (!decl) return null;
    const base = SID_ENTITIES[decl.entity] || {};
    return {
      standard:    'TM Forum SID R22',
      entity:      decl.entity,
      module:      decl.module  || base.module  || '—',
      specRef:     decl.specRef || base.specRef || 'GB922',
      openApiRef:  decl.openApiRef || null,
      note:        decl.note || null,
      attributes:  [...(base.attributes || []), ...(decl.extraAttrs || [])],
    };
  }

  return { get };
})();
